name: assignment_internshala
description: "A assignment by krushang patel"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets\fonts\light.otf
          weight: 300
        - asset: assets\fonts\regular.otf
          weight: 400
        - asset: assets\fonts\semibold.otf
          weight: 500
        - asset: assets\fonts\bold.otf
          weight: 600


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
